ARDUINO_BAUD: 9600
ARDUINO_SERIAL_PORT: /dev/ttyACM1
FLAG_FILE: /home/brad/Documents/ROS_Workspaces/simple_navigation_goals/src/simple_navigation_goals/goals/flags_2.json
PATH_FILE: /home/brad/Documents/ROS_Workspaces/simple_navigation_goals/src/simple_navigation_goals/courses/course_9_filled.json
REACH_BAUD: 9600
REACH_IP: 192.168.131.201
REACH_SERIAL_PORT: /dev/ttyACM0
ROS_MASTER_URI: http://192.168.131.11:11311
